server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/bus?allowPublicKeyRetrieval=true
    username: root
    password: cyz329329
#  redis:
#    lettuce:
#      pool:
#        max-active: -1
#        max-idle: 8
#        min-idle: 1
#        max-wait: -1
#        time-between-eviction-runs: 0
#      host: 124.222.112.65
#      port: 6379
#      timeout: 10000 # 毫秒
#      password: prod-center
#      maxAttempts: 5 # 最大尝试次数
#      connectTimeout: 3000 # 毫秒 连接超时时间
#      soTimeout: 3000 # 毫秒 socketTimeout


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.zking.mybatispluspro.model
  configuration:
    #驼峰命名规则
    map-underscore-to-camel-case: true

logging:
  file:
    path: logs/
  level:
    com.zonefun: debug

# 白名单 其中的url不需要token
base:
  white-list-url: