server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://124.222.112.65:3306/algorithm?allowPublicKeyRetrieval=true
    username: algorithm
    password: algorithm
  flyway:
    enable: false
    # 禁止清理数据库表
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用,将当前数据库初始版本设置为0
    baseline-version: 0
    # 假如已经执行了版本1和版本3，如果增加了一个版本2，下面这个选项将会允许执行版本2的脚本
    out-of-order: true
#  redis:
#    lettuce:
#      pool:
#        max-active: -1
#        max-idle: 8
#        min-idle: 1
#        max-wait: -1
#        time-between-eviction-runs: 0
#      host: 124.222.112.65
#      port: 6379
#      timeout: 10000 # 毫秒
#      password: prod-center
#      maxAttempts: 5 # 最大尝试次数
#      connectTimeout: 3000 # 毫秒 连接超时时间
#      soTimeout: 3000 # 毫秒 socketTimeout


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.zking.mybatispluspro.model
  configuration:
    #驼峰命名规则
    map-underscore-to-camel-case: true

logging:
  file:
    path: logs/
  level:
    com.glsc: debug

# 白名单 其中的url不需要token
base:
  white-list-url: